# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
 - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru() если сборка упала
notifications:
  email:
    recipients:
      - udenis80@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
    env:
      global:
        - CODECOV_TOKEN="0d8eb197-fb78-4697-8666-aa323e2afb2a"